routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ScenarioController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\TariffController;
use App\Http\Controllers\ChatController;


Route::get('/', function () {
	return redirect('/dashboard/v3');
});

Route::get('/dashboard/v3', function () {
    return view('pages/dashboard-v3');
})->name('dashboard');

// Scenario
Route::name('scenario.')->prefix('/scenario')->group(function () {
    Route::get('/index', [ScenarioController::class, 'index'])->name('index');
//    Route::get('/create', function () {
//        return view('flowchart/index');
//    })->name('create');
    Route::get('/create', [ScenarioController::class, 'create'])->name('create');
});

Route::get('/contacts', [ContactController::class, 'index'])->name('contact.index');
Route::get('/tariffs', [TariffController::class, 'index'])->name('tariff.index');
Route::get('/chats', [ChatController::class, 'index'])->name('chat.index');
Route::get('/company', function () {
    return view('pages/Company/index');
})->name('company.index');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ChatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ChatController extends Controller
{
    public function index()
    {
        return view('pages/Chat/index');
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index()
    {
        return view('pages/Contacts.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ScenarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ScenarioController extends Controller
{
    public function index()
    {
        return view('pages/Scenario/index');
    }

    public function create()
    {
        return view('/pages/Scenario/create');
    }
}

app/Http/Controllers/TariffController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TariffController extends Controller
{
    public function index()
    {
        return view('pages/Tariff/index');
    }
}

resources/views/flowchart/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

<!-- ////////////////////////////////////////////////////////////////////////
     // @license
     // This demo file is part of yFiles for HTML 2.4.
     // Copyright (c) 2000-2021 by yWorks GmbH, Vor dem Kreuzberg 28,
     // 72070 Tuebingen, Germany. All rights reserved.
     //
     // yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
     // of demo files in source code or binary form, with or without
     // modification, is not permitted.
     //
     // Owners of a valid software license for a yFiles for HTML version that this
     // demo is shipped with are allowed to use the demo source code as basis
     // for their own yFiles for HTML powered applications. Use of such programs is
     // governed by the rights and conditions as set out in the yFiles for HTML
     // license agreement.
     //
     // THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
     // WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
     // MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
     // NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
     // SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
     // TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
     // PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
     // LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
     // NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
     // SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     //
     ////////////////////////////////////////////////////////////////////////-->

  <title>Voice Assistent</title>

  <link rel="stylesheet" href="/style/demo.css">

{{--  <script src="/filesystem-warning.js"></script>--}}

  <style>
    #dndPanelContainer {
      position: absolute;
      top: 60px;
      right: 0px;
      bottom: 0;
      width: 225px;
      border-left: 5px solid #ebeef0;
      overflow: auto;
      box-sizing: border-box;
      z-index: 12;
    }

    #dndPanel {
      width: 100%;
    }

    .demo-dndPanelItem {
      margin: 10px auto;
      float: left;
    }

    .yfiles-cursor-dragdrop-copy {
      cursor: copy;
    }

    .yfiles-cursor-dragdrop-move {
      cursor: move;
    }

    .yfiles-cursor-dragdrop-link {
      cursor: alias;
    }

    .yfiles-cursor-dragdrop-scroll {
      cursor: move;
    }

    .yfiles-cursor-dragdrop-all {
      cursor: copy;
    }

    .yfiles-cursor-dragdrop-no-drop {
      cursor: no-drop;
    }

    .demo-toolbar, #graphComponent,
    .demo-left-hidden .demo-toolbar,
    .demo-left-hidden #graphComponent {
      right: 225px !important;
    }

    .yfiles-drag {
      z-index: 15;
      opacity: 0.35;
      transition: opacity .2s ease-in-out;
    }

    .yfiles-drag.hidden {
      opacity: 0;
    }
  </style>
</head>
<body class="demo-has-left">
<aside class="demo-sidebar demo-left">
  <h1 class="demo-sidebar-header">Description</h1>
  <div class="demo-sidebar-content">
    This demo provides a number of <a href="https://docs.yworks.com/yfileshtml/#/api/INodeStyle" target="_blank">INodeStyle</a>s which are shaped as common flowchart symbols.
    To use those different styles, drag them from the palette to the main graph component.

    <h2>Flowchart Layout</h2>
    There is an adjusted <a href="https://docs.yworks.com/yfileshtml/#/api/HierarchicLayout" target="_blank">HierarchicLayout</a> which considers some flowchart specialities.
    <ul>
      <li>Incoming-edges are grouped if they are many and there are also some outgoing-edges.</li>
      <li>
        The direction of edges that represent positive ('yes') or negative ('branches') can be selected in the toolbar.
      </li>
      <li>Flatwise edges can be drawn entirely to one side or just attach at the side of a node.</li>
      <li>Long paths in the graph are aligned.</li>
    </ul>
    Try out the different styles on the set of sample graphs by selecting the directions and press the layout-button.
  </div>
</aside>

<div class="demo-content">
  <div class="demo-toolbar">
    <button data-command="Open" title="Open a GraphML file" class="demo-icon-yIconOpen"></button>
    <button data-command="Save" title="Save a GraphML file" class="demo-icon-yIconSave"></button>

    <span class="demo-separator"></span>

    <button data-command="ZoomIn" title="Zoom In" class="demo-icon-yIconZoomIn"></button>
    <button data-command="ZoomOriginal" title="Zoom to original size" class="demo-icon-yIconZoomOriginal"></button>
    <button data-command="ZoomOut" title="Zoom Out" class="demo-icon-yIconZoomOut"></button>
    <button data-command="FitContent" title="Fit Content" class="demo-icon-yIconZoomFit"></button>

    <span class="demo-separator"></span>

    <select id="select-sample" data-type="ComboBox" data-command="SelectSample" title="Choose a Sample Graph">
      <option value="ProblemSolving">Sample: Problem Solving</option>
      <option value="StudentRegistration">Sample: Student Registration</option>
      <option value="eCommerce">Sample: eCommerce</option>
      <option value="ComputingFactorial">Sample: Computing Factorial</option>
      <option value="LargestNumber">Sample: Largest Number</option>
    </select>

    <span class="demo-separator"></span>

    <span>'Yes'-Branch</span> <select id="select-positive-branch-direction" data-command="SelectPositiveBranchDirection"
      title="Choose a preferred direction for edges with 'Yes'-Labels">
    <option value='same-as-flow'>Same As Flow</option>
    <option value='flatwise'>Flatwise</option>
    <option value='left-in-flow'>Left In Flow</option>
    <option value='right-in-flow'>Right In Flow</option>
    <option selected value="undefined">Undefined</option>
  </select> <span>'No'-Branch</span> <select id="select-negative-branch-direction"
      data-command="SelectNegativeBranchDirection" title="Choose a preferred direction for edges with 'No'-Labels">
    <option value='same-as-flow'>Same As Flow</option>
    <option value='flatwise'>Flatwise</option>
    <option value='left-in-flow'>Left In Flow</option>
    <option value='right-in-flow'>Right In Flow</option>
    <option selected value="undefined">Undefined</option>
  </select> <span>In-Edge Grouping</span> <select id="select-in-edge-grouping"
      data-command="SelectInEdgeGrouping" title="Choose in which way edges are grouped">
    <option value='none'>None</option>
    <option value='all'>All</option>
    <option selected value="optimized">Optimized</option>
  </select> <input type="checkbox" id="allow-flatwise-edges" class="demo-toggle-button labeled" checked/> <label
      for="allow-flatwise-edges">Allow Flatwise Edges</label>

    <span class="demo-separator"></span>

    <button id="layout" data-command="Layout" title="Run a Layout Algorithm" class="demo-icon-yIconLayout labeled">Layout</button>
  </div>

  <div id="dndPanelContainer">
    <div id="dndPanel"></div>
  </div>
  <div id="graphComponent"></div>
</div>

<script type="module" crossorigin="anonymous" src="{{asset('FlowchartDemo.js')}}"></script>
</body>
</html>

resources/views/includes/component/page-loader.blade.php
<!-- begin #page-loader -->
<div id="page-loader" class="fade show"><span class="spinner"></span></div>
<!-- end #page-loader -->

resources/views/includes/component/scroll-top-btn.blade.php
<!-- begin scroll to top btn -->
<a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
<!-- end scroll to top btn -->

resources/views/includes/footer.blade.php
<!-- begin #footer -->
<div id="footer" class="footer">
	&copy; 2020 Color Admin Responsive Admin Template - Sean Ngu All Rights Reserved
</div>
<!-- end #footer -->

resources/views/includes/head.blade.php
<meta charset="utf-8" />
<title>Voice Assistent | @yield('title')</title>
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
<meta content="" name="description" />
<meta content="" name="author" />

<!-- ================== BEGIN BASE CSS STYLE ================== -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
<link href="/assets/css/default/app.min.css" rel="stylesheet" />
<!-- ================== END BASE CSS STYLE ================== -->

@stack('css')

resources/views/includes/header-mega-menu.blade.php
<!-- begin navbar-collapse -->
<div class="collapse navbar-collapse" id="top-navbar">
	<ul class="nav navbar-nav">
		<li class="dropdown dropdown-lg">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-th-large fa-fw mr-1 mr-md-0"></i> Mega <b class="caret ml-1 ml-md-0"></b></a>
			<div class="dropdown-menu dropdown-menu-lg">
				<div class="row">
					<div class="col-lg-4 col-md-4">
						<div class="f-w-700 text-inverse mb-2">UI Kits</div>
						<div class="row m-b-20">
							<div class="col-lg-6">
								<ul class="nav d-block">
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> FontAwesome</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Ionicons</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Simple Line Icons</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Typography</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Media Object</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Widget Boxes</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Tabs & Accordions</a></li>
								</ul>
							</div>
							<div class="col-lg-6">
								<ul class="nav d-block">
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Unlimited Nav Tabs</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Modal & Notification</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Buttons</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-4">
						<div class="f-w-700 text-inverse mb-2">Page Options <span class="label label-pink ml-1">11</span></div>
						<div class="row m-b-20">
							<div class="col-lg-6">
								<ul class="nav d-block">
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Blank Page</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Page with Footer <span class="badge badge-success pt-1 pb-1">NEW</span></a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Page without Sidebar</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Page with Right Sidebar</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Page with Minified Sidebar</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Page with Two Sidebar</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Page with Line Icons</a></li>
								</ul>
							</div>
							<div class="col-lg-6">
								<ul class="nav d-block">
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Full Height Content</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Page with Mega Menu</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Page with Light Sidebar</a></li>
									<li><a href="javascript:;" class="text-ellipsis text-muted"><i class="fa fa-chevron-right fa-fw text-inverse"></i> Page with Large Sidebar</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-4">
						<div class="f-w-700 text-inverse mb-2">Paragraph</div>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis libero purus, fermentum at libero convallis, auctor dignissim mauris. Nunc laoreet pellentesque turpis sodales ornare. Nunc vestibulum nunc lorem, at sodales velit malesuada congue. Nam est tortor, tincidunt sit amet eros vitae, aliquam finibus mauris.
						</p>
						<p>
							Fusce ac ligula laoreet ante dapibus mattis. Nam auctor vulputate aliquam. Suspendisse efficitur, felis sed elementum eleifend, ipsum tellus sodales nisi, ut condimentum nisi sem in nibh. Phasellus suscipit vulputate purus at venenatis. Quisque luctus tincidunt tempor.
						</p>
					</div>
				</div>
			</div>
		</li>
		<li>
			<a href="javascript:;">
				<i class="fa fa-gem fa-fw mr-1 mr-md-0"></i> Client
			</a>
		</li>
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				<i class="fa fa-database fa-fw mr-1 mr-md-0"></i> New <b class="caret ml-1 ml-md-0"></b>
			</a>
			<div class="dropdown-menu">
				<a href="javascript:;" class="dropdown-item">Action</a>
				<a href="javascript:;" class="dropdown-item">Another action</a>
				<a href="javascript:;" class="dropdown-item">Something else here</a>
				<div class="dropdown-divider"></div>
				<a href="javascript:;" class="dropdown-item">Separated link</a>
				<div class="dropdown-divider"></div>
				<a href="javascript:;" class="dropdown-item">One more separated link</a>
			</div>
		</li>
	</ul>
</div>
<!-- end navbar-collapse -->

resources/views/includes/page-js.blade.php
<!-- ================== BEGIN BASE JS ================== -->
<script src="/assets/js/app.min.js"></script>
<script src="/assets/js/theme/default.min.js"></script>
<!-- ================== END BASE JS ================== -->

@stack('scripts')

resources/views/layouts/empty.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
	@include('includes.head')
</head>
@php
	$bodyClass = (!empty($boxedLayout)) ? 'boxed-layout ' : '';
	$bodyClass .= (!empty($paceTop)) ? 'pace-top ' : '';
	$bodyClass .= (!empty($bodyExtraClass)) ? $bodyExtraClass . ' ' : '';
@endphp
<body class="{{ $bodyClass }}">
	@include('includes.component.page-loader')
	
	@yield('content')
			
	@include('includes.page-js')
</body>
</html>

resources/views/pages/Scenario/create.blade.php
@extends('layouts.default')

@section('title', 'Ssenariy yaratish')

@section('content')
	<!-- begin breadcrumb -->
    <ol class="breadcrumb float-xl-right">
        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Bosh sahifa</a></li>
        <li class="breadcrumb-item"><a href="{{ route('scenario.index') }}">Ssenariylar</a></li>
        <li class="breadcrumb-item active">Ssenariy yaratish</li>
    </ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header">Ssenariy yaratish</h1>
	<!-- end page-header -->

	<!-- begin row -->
	<div class="row">
		<!-- begin col-12 -->
		<div class="col-12">
			<!-- begin panel -->
			<div class="panel panel-inverse" data-sortable-id="form-stuff-12">
				<!-- begin panel-heading -->
				<div class="panel-heading">
					<h4 class="panel-title">Ssenariy </h4>
					<div class="panel-heading-btn">
						<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
						<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
						<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
					</div>
				</div>
				<!-- end panel-heading -->
				<!-- begin panel-body -->
				<div class="panel-body">
                    <form action="" class="form-group" method="get" enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-xl-6 col-md-6">
                                <div class="form-group">
                                    <label for="name">Ssenariy nomi</label>
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-xl-6 col-md-6">
                                <div class="form-group">
                                    <label for="name">Ssenariy tasnifi</label>
                                    <textarea class="form-control"> </textarea>
                                </div>
                            </div>
{{--                            <div class="col-xl-2 col-md-6">--}}
{{--                                <button type="button" class="btn btn-primary mt-4" onclick="">--}}
{{--                                    <i class="fa fa-plus-square"></i> Blok qo'shish--}}
{{--                                </button>--}}
{{--                            </div>--}}
                        </div>
                        <div class="row">
                            <img src="/image/block.png" width="100%">
                        </div>
                        <br>
                            <a href="{{route('scenario.index')}}" class="btn btn-danger float-right">
                                <i class="fas fa-arrow-circle-left"></i>
                                Ortga
                            </a>
                            <a href="{{route('scenario.index')}}" class="btn btn-success float-right mr-2">
                                <i class="fas fa-arrow-circle-left"></i>
                                Saqlash
                            </a>
                            <a href="{{route('scenario.index')}}" class="btn btn-info float-right mr-2">
                                <i class="fas fa-arrow-circle-left"></i>
                                Chop etish
                            </a>
                    </form>

                </div>
				<!-- end panel-body -->
				<!-- end hljs-wrapper -->
			</div>
			<!-- end panel -->
		</div>
		<!-- end col-6 -->
	</div>
	<!-- end row -->
@endsection

@push('scripts')
	<script src="/assets/plugins/highlight.js/highlight.min.js"></script>
	<script src="/assets/js/demo/render.highlight.js"></script>
@endpush

resources/views/pages/Scenario/index.blade.php
@extends('layouts.default')

@section('title', 'Ssenariylar')

@push('css')
	<link href="/assets/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
	<link href="/assets/plugins/datatables.net-fixedcolumns-bs4/css/fixedcolumns.bootstrap4.min.css" rel="stylesheet" />
@endpush

@section('content')
	<!-- begin breadcrumb -->
	<ol class="breadcrumb float-xl-right">
		<li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Bosh sahifa</a></li>
		<li class="breadcrumb-item active">Ssenariylar</li>
	</ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header">Ssenariylar</h1>
	<!-- end page-header -->
	<!-- begin row -->
	<div class="row">
		<!-- begin col-12 -->
		<div class="col-xl-12">
			<!-- begin panel -->
			<div class="panel panel-inverse">
				<!-- begin panel-heading -->
				<div class="panel-heading">
					<h4 class="panel-title">Ssenariylar</h4>
                    <a href="{{ route('scenario.create') }}" class="btn btn-xs btn-primary mr-3">
                        <i class="fa fa-plus"></i> Yangi ssenariy </a>
					<div class="panel-heading-btn">
						<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
						<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
						<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
					</div>
				</div>
				<!-- end panel-heading -->
				<!-- begin panel-body -->
				<div class="panel-body">
					<table id="data-table-fixed-columns" class="table table-striped table-bordered table-td-valign-middle">
						<thead>
							<tr>
								<th width="1%"></th>
								<th class="text-nowrap">Nomi</th>
								<th class="text-nowrap">Status</th>
								<th class="text-nowrap">Yaratilgan vaqti</th>
								<th class="text-nowrap">O'zgartirilgan vaqti</th>
								<th class="text-nowrap">Amallar</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td width="1%" class="f-s-600 text-inverse">1</td>
								<td>Aksiyalar</td>
								<td>Aktiv</td>
								<td>25.12.2021</td>
								<td>25.12.2021</td>
                                <td class="text-center">
                                    <a href="#" class="btn  btn-icon btn-success mr-1"><span class="fas fa-eye "></span></a>
                                    <button type="button" class="btn btn-icon btn-primary mr-1 edit">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                    <button type="button" class="btn btn-icon btn-danger delete_button delete">
                                        <i class="fas fa-trash  text-white"></i>
                                    </button>
                                </td>
							</tr>
						</tbody>
					</table>
				</div>
				<!-- end panel-body -->
			</div>
			<!-- end panel -->
		</div>
		<!-- end col-10 -->
	</div>
	<!-- end row -->
@endsection

@push('scripts')
	<script src="/assets/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
	<script src="/assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
	<script src="/assets/plugins/datatables.net-fixedcolumns/js/dataTables.fixedcolumns.min.js"></script>
	<script src="/assets/plugins/datatables.net-fixedcolumns-bs4/js/fixedcolumns.bootstrap4.min.js"></script>
	<script src="/assets/js/demo/table-manage-fixed-columns.demo.js"></script>
@endpush